---
name: On Deploy

"on":
  workflow_dispatch:
    inputs:
      environment:
        description: Target environment
        required: true
        type: choice
        options:
          - stage
          - prod
        default: stage

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Checkout code
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6
        with:
          persist-credentials: false

      - name: Run on-release flow
        uses: cloudvoyant/premise@120ba28d0305e8215f10bfcdcbc92fac2257e782
        with:
          flow: on-release
          environment: ${{ inputs.environment }}
          install-premise: build
